---
deployment:
    tasks:
        - export DEPLOYPATH=/home/blexteza/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp style.css $DEPLOYPATH
        - /bin/cp -R images $DEPLOYPATH
